### ISSUE TITLE
remove pandas and django as test deps

### ISSUE THREAD

**Issue by beckermr** [conda-forge/hypothesis-feedstock#545]
These dependencies are causing extremely odd cycles in the bot graph. I suggest instead of adding an extra output with the tests or simply removing them.

xref: https://github.com/regro/cf-scripts/issues/1331

**Comment by beckermr** [comment]
cc @conda-forge/bot any suggestions or thoughts here?

**Comment by CJ-Wright** [comment]
We could try to break cycles by not honoring test deps (as a second order thing), but that may cause a bunch of failing builds all over the place. I think better understanding of why those deps are testing deps could help with the decision making.

**Comment by beckermr** [comment]
the builds will fail even if the bot ignores them as you say. if this really is essential, then we need a way to skip optional tests or we need a separate feedstock with them

**Comment by beckermr** [comment]
@conda-forge/hypothesis thoughts here?

**Comment by beckermr** [comment]
closing in favor of a fix on the bot side
