### ISSUE TITLE
Cannot install (with mamba)

### ISSUE THREAD

**Issue by renefritze** [conda-forge/hypothesis-feedstock#730]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When installing version 6.52.3 I get this [error](https://github.com/pymor/pymor/runs/7618149039?check_suite_focus=true#step:8:15)

```
Encountered problems while solving:
  - nothing provides exceptiongroup >=1.0.0rc8 needed by hypothesis-6.52.3-pyhd8ed1ab_0
```

This [change](https://github.com/conda-forge/hypothesis-feedstock/commit/75ce44e279b5156cf87f6630e711ba01f2132386) apparently then is the culprit.

Is this maybe a problem with mamba? Since obviously the package/recipe build here succeeded without errors?

### Installed packages

```shell
This is the base env

    Package              Version  Build               Channel                 Size
  ──────────────────────────────────────────────────────────────────────────────────
    Install:
  ──────────────────────────────────────────────────────────────────────────────────
  
    + bzip2                1.0.8  h0d85af4_4          conda-forge/osx-64     159kB
    + ca-certificates  2022.6.15  h033912b_0          conda-forge/osx-64     153kB
    + libffi               3.4.2  h0d85af4_5          conda-forge/osx-64      51kB
    + libzlib             1.2.12  hfe4f2af_2          conda-forge/osx-64      65kB
    + ncurses                6.3  h96cf925_1          conda-forge/osx-64     937kB
    + openssl              3.0.5  hfe4f2af_0          conda-forge/osx-64       3MB
    + pip                 22.2.1  pyhd8ed1ab_0        conda-forge/noarch       2MB
    + python              3.9.13  hf8d34f4_0_cpython  conda-forge/osx-64      13MB
    + python_abi             3.9  2_cp39              conda-forge/osx-64       4kB
    + readline             8.1.2  h3899abd_0          conda-forge/osx-64     272kB
    + setuptools          63.3.0  py39h6e9494a_0      conda-forge/osx-64       1MB
    + sqlite              3.39.2  hd9f0692_0          conda-forge/osx-64       2MB
    + tk                  8.6.12  h5dbffcc_0          conda-forge/osx-64       4MB
    + tzdata               2022a  h191b570_0          conda-forge/noarch     124kB
    + wheel               0.37.1  pyhd8ed1ab_0        conda-forge/noarch      32kB
    + xz                   5.2.5  haf1e3a3_1          conda-forge/osx-64     233kB
    + zlib                1.2.12  hfe4f2af_2          conda-forge/osx-64      95kB
```

### Environment info

```shell
Best I can do for this is https://github.com/pymor/pymor/runs/7618149039?check_suite_focus=true#step:5:2

The error happens in all our macos, linux and windows builders. These all try to install the same packages, and all currently fail with above message.
```

**Comment by jochym** [comment]
Does it install with conda?

**Comment by renefritze** [comment]
I've setup a minimal [Dockerfile](https://github.com/renefritze/hypothesis-conda-issue/blob/main/Dockerfile) to replicate my problem. That setup also cannot install hypothesis (which conda), but with a [different problem](https://github.com/renefritze/hypothesis-conda-issue/runs/7626823927?check_suite_focus=true#step:3:442)

**Comment by renefritze** [comment]
So for some reason mamba does not consider the package with rc2 (latest in conda forge, current is rc8) for exceptiongroup to be installable.  [See here](https://github.com/renefritze/hypothesis-conda-issue/runs/7669612733?check_suite_focus=true#step:3:213) via this [Dockerfile](https://github.com/renefritze/hypothesis-conda-issue/blob/mamba/Dockerfile)

```
pip install exceptiongroup
```

works however. There seems to be no way to make mamba accept pre-release versions. 

Plain conda also fails to install `exceptiongroup` directly (w/o any version constraint).
[Dockerfile](https://github.com/renefritze/hypothesis-conda-issue/blob/conda/Dockerfile) and [build result](https://github.com/renefritze/hypothesis-conda-issue/runs/7669766532?check_suite_focus=true#step:3:154)

Would it be alright with you @jochym to remove the dependency for exceptiongroup until they have a final, non-RC, release?

**Comment by renefritze** [comment]
> Would it be alright with you @jochym to remove the dependency for exceptiongroup until they have a final, non-RC, release?

Just in case I've prepared a PR for that.

**Comment by renefritze** [comment]
Since #733 made it clear to me that `exceptiongroup` is actually a hard dependency, I guess there's nothing really to be done for anybody who's using mamba, right?
Maybe pre-installing it with pip before using mamba to install hypothesis?
