### ISSUE TITLE
Please make this a noarch package

### ISSUE THREAD

**Issue by mattip** [conda-forge/hypothesis-feedstock#748]
Are there any machine-specific code paths in hypothesis? If not, it would be nice to convert this to a `noarch` package to save resources.

**Comment by jochym** [comment]
I am probably too stupid, but why the zoneinfo needs to be platform-specific? (except if we consider the Earth is a platform ;)

**Comment by mattip** [comment]
I think the zoneinfo problem is cinflating two things. noar h implies this runs on any machine. There must be a way for the package to have a pre-python3.9 dependency on zoneinfo, while having a single noarch package.

**Comment by mattip** [comment]
Is backports-zoneinfo needed by hypothesis or only because of django? If the latter, django already installs it ...

**Comment by ocefpaf** [comment]
It is noarch (for a while now). I guess we can close this one.
