### ISSUE TITLE
Staying current with Hypothesis releases

### ISSUE THREAD

**Issue by Zac-HD** [conda-forge/hypothesis-feedstock#8]
Upstream issue: HypothesisWorks/hypothesis-python#555

In short, a new and terrifying age of continuous deployment is here for Hypothesis - every pull with changes to ./src automatically results in a new release, averaging weekly but rarely up to several times per day.  Obviously trying to keep up by hand is not working, and as a conda-forge user and Hypothesis maintainer this seems like something I can help with.  So:

- To what extent can updates to the feedstock be automated?
- How much of this work can we do upstream?  (scripts already push tags, build and deploy to PyPI, etc)

**Comment by jochym** [comment]
It is a problem not only for hypothesis. A number of projects use "always deployable master" scheme. Which is good for users but terrible for packagers. Paradoxically pypi works better then conda-forge with this due to the manual parts of the workflow. I do not know of any automatic solutions deploying to conda-forge on new pypi release. If there is one I would like to know about it. I could use it for multiple projects I am involved with. In my opinion this should be integrated with upstream release pipeline the same way pypi release is (e.g. as final stage of CI run).

**Comment by Zac-HD** [comment]
Could our [deploy.py](https://github.com/HypothesisWorks/hypothesis-python/blob/master/scripts/deploy.py) push a commit to this repo updating the version and hash?  f18d8e2264827cfe868c60043019abebb9689190 seems to indicate that would be enough.

**Comment by jochym** [comment]
Yes, in principle. The point is it would be against the rules as I understand them. The correct procedure is supposed to be:

1. commit new version data to your fork of the feedstock
2. (optional) re-render the feedstock with updated smithy
2. create PR from this commit against the feedstock
3. wait for the CI test to come clean (this is probably the most problematic if there are no webhooks for signaling the status).
4. merge the PR

Blind pushing into the feedstock repo is considered to be against the rules. Justifiably so. It has a potential of making inconsistent packages across  architectures and other problems. Do you thing this could be implemented?

**Comment by Zac-HD** [comment]
Ah, that is a better process.  

Steps 1, 2, and 3 could easily be done by our CI deploy task, which would mean you only need to click merge.  Not automated, but close enough I hope?

Steps 4 and 5 are tricky, but I want to set up the same logic (auto-merge pulls from a specific bot iff tests pass) upstream for pyup.io pulls to update dependencies.  If that works out, I'd be happy to get it working for these too.

**Comment by isuruf** [comment]
I think having very frequent builds would have an impact on our CI resources. @conda-forge/core will have to confirm that.
I use a clone of the feedstock to upload dev versions (not the same thing, I know) automatically without PRs to my own channel. This might work for you if having very frequent releases is a strain on conda-forge CI.

**Comment by Zac-HD** [comment]
Given that Hypothesis is a pure-Python package with no dependencies, I don't think the load would be too bad - we average around one release per week.

**Comment by jjhelmus** [comment]
If the conditional run requirements on `enum34` can be removed then it would be possible to make [`noarch: python`](https://www.continuum.io/blog/developer-blog/condas-new-noarch-packages) packages for Hypothesis.  This could significantly reduce the load on the CI, instead of building 16 packages per release (4 version of python x 4 platforms), only a single package would be built.

**Comment by Zac-HD** [comment]
Hmm.  We only define three enums, but they're fairly widely used and might be public API.  @DRMacIver would know more.

Would it be possible to use a noarch package for all Python3 versions anyway?

**Comment by mwcraig** [comment]
What is the expected release frequency? In the first message it said several times per day, but later on it says several times per month. The latter is not a problem for a small python package, but the former might be...

**Comment by Zac-HD** [comment]
Average is ~weekly.  Highest bursts are 2-3 per day, but that's certainly not common.

**Comment by jochym** [comment]
Right now I am trying to solve (partially) the release problem with pypi-notifier - at least I should know when something should be done.

**Comment by jochym** [comment]
I have managed to semi-automatise the procedure (up to making the PR) by some third party tools. I can drop the setup here if anybody is interested. 
But I have a huge problem with new  3.31.2 version - I had to block py27 build to make it work. I would appreciate if somebody would review the package and my PR (https://github.com/conda-forge/hypothesis-feedstock/pull/15). @Zac-HD @jjhelmus ?

**Comment by DRMacIver** [comment]
I see there have been some problems on this recently. I'm not sure what happened with the 3.33.0 release (I can see that it was broken, I just don't know enough about conda packaging to understand *why*), but is there anything we can do to help get you unstuck? What are the actual problems that you're having? It's hard to tell from the PR link.

**Comment by jochym** [comment]
Thanks for the message @DRMacIver .  Essentially the install/testing stage of the CI stopped working. Even simple imports errored. If you have problem locating build logs I can post the links to build logs.
I can also prepare a new PR for us to work on this issue.

**Comment by DRMacIver** [comment]
Some links would be useful, as I can't see any obvious problems in the build logs linked from #15... but at least one obvious problem is that I don't think you're adding the new dependencies? You've got attrs and coverage listed as build dependencies, but they're actual runtime dependencies.

And yes, if you wouldn't mind preparing a new PR that would be helpful! I'm happy to assist on any Hypothesis side problems but I have exactly zero knowledge of how conda forge works.

**Comment by jochym** [comment]
OK. Thanks @DRMacIver. I just generated a new PR for this work https://github.com/conda-forge/hypothesis-feedstock/pull/19 based on the 3.36.0. Let us work on this version instead of beating a dead horse of previous attempt.

**Comment by CJ-Wright** [comment]
I think that the @regro-cf-autotick-bot can help some with this.

Also one can specify a noarch package with `python >=3.5` and it will do the right thing.

**Comment by Zac-HD** [comment]
🎉 this feedstock is [staying up to date really well recently](https://anaconda.org/conda-forge/hypothesis/files) - with delays at longest on the order of a few days instead of a few months.  I'm therefore closing the issue.
